#1856 Fix for app crashing when using save as option from browser
TeamAmaze/AmazeFileManager pull request #1958
Opened 2020-08-16 20:26 UTC by pcsaunak

## PR Info
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

2020-08-17 06:05 UTC, pcsaunak commented
@VishalNehra Can you cross check this and let me know if you see any issues here?

2020-08-18 20:39 UTC, VishalNehra commented
Great work! (:
A few things:
Please close #1955 as it's stale now.
Please fill details in this PR description, write Fixes #1856 (this will automatically close the issue on merging this PR).
Tick the checks in description, whichever you performed. Also write your device info in relevant field there.
Assign Projects -> roadmap -> click press outside, from dropdown select the release in which you want this to be pushed.

Just few non technical things and we're good to go! (:

2020-08-18 20:50 UTC, VishalNehra requested changes

2020-08-18 20:50 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
> +                FileUtil.mktextfile(data, getCurrentMainFragment().getCurrentPath(), fileName);
If you notice, the call is sync, so saving the data occurs in main thread, which is not recommended. 
Please write this call around in runnable as follows.
```AppConfig.runInBackground(() -> FileUtil.mktextfile(data, getCurrentMainFragment().getCurrentPath(), fileName));```

2020-08-18 20:50 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java
> +      out = new FileOutputStream(f);
Pass a second argument as false to FileOutputStream constructor, it'll overwrite instead of appending. No need to delete the file first.

2020-08-18 20:50 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java
> +      f.delete();
Redundant call.

2020-08-20 07:12 UTC, VishalNehra approved these changes

2020-08-20 07:14 UTC, merged