Null check of ApplicationInfo.sourceDir
TeamAmaze/AmazeFileManager pull request #2116
Opened 2020-12-04 00:17 UTC by TranceLove

## PR Info
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1604

#### Release  
Addresses release/3.5
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

2020-12-04 04:47 UTC, VishalNehra approved these changes

2020-12-04 21:23 UTC, EmmanuelMess requested changes

2020-12-04 21:23 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/asynchronous/loaders/AppListLoader.java
> +      if (object.sourceDir != null) {
Invert the if to "if(object.sourceDir == null) { <log> continue;}" to reduce indentation level.

2020-12-06 21:20 UTC, EmmanuelMess approved these changes

2020-12-06 21:21 UTC, EmmanuelMess commented
This should go to hotfix/1.5.2

2020-12-09 20:46 UTC, VishalNehra approved these changes

2020-12-10 12:52 UTC, VishalNehra approved these changes

2020-12-10 12:53 UTC, merged