Fix implicit build errors
TeamAmaze/AmazeFileManager pull request #2124
Opened 2020-12-08 06:37 UTC by TranceLove

Close database on test case finish to prevent leaks (hopefully)

## PR Info

#### Release  
Addresses release/3.5
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
#### Build tasks success  
Successfully running following tasks on local 
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

2020-12-08 16:42 UTC, TranceLove commented
As of this round it becomes apparent that `SshHyridFileTest` is the culprit. Couldn't find the reason, but it seems to be the hotspot where the `Illegal connection pointer` exception was thrown.

2020-12-10 03:57 UTC, VishalNehra approved these changes

2020-12-10 03:59 UTC, VishalNehra requested changes

2020-12-10 03:59 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshClientUtils.java
> +                .doOnError(Throwable::printStackTrace)
Is catch block needed after this change or is it redundant?

2020-12-10 07:10 UTC, VishalNehra approved these changes

2020-12-10 07:10 UTC, merged