CIFSContext pooling
TeamAmaze/AmazeFileManager pull request #2171
Opened 2020-12-31 07:58 UTC by TranceLove

## PR Info
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #
-or-   
Addresses #2086

#### Release  
Addresses release/3.6
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info
Restrict redundant creation of CIFSContext/BaseContext instances, to hopefully fix #2086.

BaseContexts are saved using in a map, similar to SshConnectionPool, using smb://<credentials>@<host><additional parameters as query string> as key, to allow reusing connections if same credentials (and settings) are used on connecting SMB server.

2021-01-03 12:33 UTC, VishalNehra commented
Changes seem fine. Will test once.

2021-01-04 19:05 UTC, EmmanuelMess requested changes

2021-01-04 19:05 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/filesystem/smb/CifsContexts.kt
> +    interface Factory {
Factory is redundant, we should probably add it when we need it.

2021-01-05 05:53 UTC, VishalNehra commented
Awesome work @TranceLove operations have become much faster with these changes!

2021-01-05 05:53 UTC, VishalNehra approved these changes

2021-01-05 15:36 UTC, EmmanuelMess approved these changes
Had to apply #2180.

2021-01-05 15:37 UTC, merged