Reopen SMB dialog on failed load list
TeamAmaze/AmazeFileManager pull request #2196
Opened 2021-01-06 07:12 UTC by VishalNehra

## PR Info
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2195 
-or-   
Addresses #

#### Release  
Addresses release/3.5
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

2021-01-06 14:55 UTC, TranceLove submitted a review, later dismissed
Works fine on LG Nexus 5x running AOSPExtended (9.0). +1.

2021-01-08 16:24 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java
> +              setListElements(data.second, back, path, data.first, false, isPathLayoutGrid);
We're handling the null case in setListElements. We'll cancel and navigate to home directory.

2021-01-09 03:25 UTC, TranceLove requested changes

2021-01-09 03:25 UTC, TranceLove commented on app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java
> +              setListElements(data.second, back, path, data.first, false, isPathLayoutGrid);
Sorry... looks like not.

Tested using Fairphone 3 running LineageOS 16.0 (9.0) with 2 cases
1. browse a SMB server on an entirely different subnet than where I am
2. browse a restricted share, which is visible to user but simply accessible by only designated users

Corresponding smb.conf entry is as follows:
```
[tmp]
    comment = Temporary directory on server
    path = /tmp
    browseable = yes
    read only = yes
    guest ok = no
    valid users = root
```
Both ended crashing the app 

## Exception
* User Action: UI Error
* Request: Application crash
* Version: 3.5.3
* OS: Linux Android 9 - 28
* Device: FP3
* Model: FP3
* Product: FP3
<details><summary><b>Crash log </b></summary><p>


java.lang.NullPointerException: Attempt to read from field 'java.lang.Object androidx.core.util.Pair.second' on a null object reference
 at com.amaze.filemanager.ui.fragments.MainFragment.lambda$loadlist$3$MainFragment(MainFragment.java:954)
 at com.amaze.filemanager.ui.fragments.-$$Lambda$MainFragment$9qQv21X8JwPlLXi_cDXfu4p-_VI.onAsyncTaskFinished(Unknown Source:8)
 at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:270)
 at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.onPostExecute(LoadFilesListTask.java:67)
 at android.os.AsyncTask.finish(AsyncTask.java:695)
 at android.os.AsyncTask.access$600(AsyncTask.java:180)
 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:193)
 at android.app.ActivityThread.main(ActivityThread.java:6718)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)


</details>
<hr>

The null check can prevent crash, which case 1 would give the SMB connect dialog back, and case 2 will simply not respond. Not good in UX, but at least not crash - you may give user a Toast for this.

2021-01-09 05:19 UTC, TranceLove commented
build test apk

2021-01-09 08:16 UTC, TranceLove approved these changes
Sorry for the late reply. Checked OK on Fairphone 3 running LineageOS 16.0 (9.0).

+1.

2021-01-09 08:36 UTC, merged