Fixes issue #2244 -> NPE on SwipeRefreshView while searching
TeamAmaze/AmazeFileManager pull request #2432
Opened 2021-04-24 22:31 UTC by VishnuSanal

## PR Info
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2244 (Hopefully!)

#### Release  
Addresses release/3.6
  
#### Test cases
- [x] Covered
  
#### Manual testing
- [x] Done  

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2021-04-24 22:53 UTC, VishnuSanal commented
Should I log that?

2021-04-25 11:49 UTC, VishalNehra requested changes

2021-04-25 11:49 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java
> +    if (mainFragment == null) return;
I think before returning null, should show a toast saying 'Operation unsuccessful' or something similar.

2021-04-25 16:59 UTC, VishalNehra approved these changes

2021-04-29 21:36 UTC, EmmanuelMess approved these changes

2021-04-29 21:36 UTC, merged