Bugfix/2439 Fix OpenFile bottom sheet dismiss issue on swiping
TeamAmaze/AmazeFileManager pull request #2532
Opened 2021-06-03 12:14 UTC by VishalNehra

## Description

#### Issue tracker   

Fixes #2439 

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

2021-06-03 19:07 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt
> +            val behavior = BottomSheetBehavior.from(bottomSheet!!)
Please remove !!

2021-06-03 19:08 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt
> +                .findViewById<View>(com.google.android.material.R.id.design_bottom_sheet)
Please fix findViewById<View> with a cast later.

2021-06-03 19:08 UTC, EmmanuelMess requested changes
See comments

2021-06-05 15:08 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt
> +                .findViewById(com.google.android.material.R.id.design_bottom_sheet)
This should be directly parametrized as FrameLayout (findViewById<FrameLayout>)

2021-06-05 15:22 UTC, EmmanuelMess commented
Pressing on the top of the bottom sheet and swiping down doesn't do anything.

2021-06-05 15:25 UTC, VishalNehra commented
@EmmanuelMess Yea, basically all gestures now lead to expanded state. Couldn't find any other way to fix this. 
I feel this doesn't effect the UX much as pressing outside the sheet or device back button closes the sheet still.

2021-06-06 22:09 UTC, EmmanuelMess approved these changes

2021-06-07 01:57 UTC, EmmanuelMess commented
@VishalNehra codacy failed.

2021-06-07 02:00 UTC, EmmanuelMess commented
Lets test if I can trigger a codacy check with an empty commit.

2021-06-07 02:47 UTC, merged