Add liberapay as funding
TeamAmaze/AmazeFileManager pull request #2601
Opened 2021-06-09 08:21 UTC by VishalNehra

## Description

#### Issue tracker   

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

2021-06-09 15:25 UTC, EmmanuelMess commented on README.md
> +[![Liberpay](https://img.shields.io/liberapay/receives/Team-Amaze.svg?logo=liberapay)](https://liberapay.com/Team-Amaze/donate)
Please move this one line down, that line is for code status badges.

2021-06-09 21:14 UTC, EmmanuelMess requested changes
See comment

2021-06-10 14:16 UTC, EmmanuelMess approved these changes

2021-06-10 14:17 UTC, EmmanuelMess commented
Wait, why is liberapay in indian rupies?

2021-06-10 14:39 UTC, VishalNehra commented
Not sure. Will check.

2021-06-11 08:03 UTC, TranceLove submitted a review, later dismissed
Seems it can switch automatically to the currency according to where the device is at ~~now~~ at my side. Should be good to go.

2021-06-11 13:48 UTC, EmmanuelMess approved these changes
Doesn't have argentinian peso :(, no  matter though.

2021-06-11 14:59 UTC, Unpublished commented on README.md
> +[![Liberpay](https://img.shields.io/liberapay/receives/Team-Amaze.svg?logo=liberapay)](https://liberapay.com/Team-Amaze/donate)
```suggestion
[![Liberapay](https://img.shields.io/liberapay/receives/Team-Amaze.svg?logo=liberapay)](https://liberapay.com/Team-Amaze/donate)  
```

2021-06-12 11:45 UTC, merged