Fixed issue where dialogs wouldn't allow multiline input.
TeamAmaze/AmazeFileManager pull request #2639
Opened 2021-06-18 07:29 UTC by unkownfire

## Description
Edited dialog_singleedittext.xml to allow multiline text input. This fixes bug #2634 and allows the rename dialog box to have multiline input. However, this also makes it so that all other dialogs that use dialog_singleedittext.xml also have support for multiline input. I don't know if this is the desired outcome, as the issue only specifically names the rename dialog box. (This is also my first contribution to an open source project ever). 

#### Issue tracker   

Fixes #2634

#### Manual tests
- [x] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2021-06-18 18:59 UTC, VishalNehra requested changes

2021-06-18 18:59 UTC, VishalNehra commented on app/src/main/res/layout/dialog_singleedittext.xml
> +
why line break? please remove

2021-06-18 18:59 UTC, VishalNehra commented on app/src/main/res/layout/dialog_singleedittext.xml
> +
please remove redundant line break.

2021-06-18 20:53 UTC, VishalNehra commented
Build test apk

2021-06-18 21:06 UTC, VishalNehra approved these changes

2021-06-20 12:07 UTC, VishalNehra approved these changes

2021-06-24 18:58 UTC, EmmanuelMess approved these changes

2021-06-24 18:58 UTC, merged