Bump 3.7
TeamAmaze/AmazeFileManager pull request #2643
Opened 2021-06-18 15:36 UTC by TranceLove

Rebase current `master` to `release/3.7` branch, and bumped version up to 3.7 at build.gradle.

2021-06-18 16:03 UTC, VishalNehra requested changes

2021-06-18 16:03 UTC, VishalNehra commented on app/src/main/res/values/translators.xml
> +    <string name="app_version" translatable="false">v3.6.1</string>
Please change to 3.7.0 here as well

2021-06-19 09:31 UTC, VishalNehra approved these changes

2021-06-19 21:44 UTC, EmmanuelMess approved these changes

2021-06-19 21:44 UTC, merged