Update Strings
TeamAmaze/AmazeFileManager pull request #2787
Opened 2021-09-09 20:52 UTC by VishnuSanal

## Description

#### Issue tracker   
Fixes #2653 

#### Manual tests
- [x] Done  

#### Build tasks success
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Additional info

Should the string names be renamed too?

2021-09-09 23:50 UTC, EmmanuelMess commented
Please delete old strings and create new ones so that the translations are redone.

2021-09-09 23:50 UTC, EmmanuelMess requested changes
Please delete old strings and create new ones so that the translations are redone.

2021-09-12 13:25 UTC, EmmanuelMess approved these changes

2021-09-19 07:25 UTC, VishalNehra approved these changes

2021-09-19 07:25 UTC, merged