CompressedExplorerFragment refactorings
TeamAmaze/AmazeFileManager pull request #2796
Opened 2021-09-12 05:28 UTC by TranceLove

## Description
Continuation of #2754 to improve code quality after converting CompressedExplorerFragment to Kotlin.

Although based on 3.6.2, not necessarily to be included in 3.6.2 release.

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  
- Device: Pixel 2 emulator
- OS: Android 11
Test for basic functionality for possible regressions

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2021-09-12 23:59 UTC, EmmanuelMess requested changes
This still has quite a few `!!`

2021-09-13 00:52 UTC, EmmanuelMess commented
Sorry, I broke something, so I reverted my changes.

2021-09-13 12:52 UTC, EmmanuelMess approved these changes

2021-09-19 07:23 UTC, VishalNehra approved these changes

2021-09-19 07:23 UTC, merged