rename dummy file
TeamAmaze/AmazeFileManager pull request #2815
Opened 2021-09-19 08:12 UTC by VishnuSanal

## Description

#### Issue tracker   
Fixes #2804 

#### Manual tests
- [x] Done  

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2021-09-19 12:04 UTC, EmmanuelMess commented
Please create a global constant somewhere that makes sense.

2021-09-19 12:04 UTC, EmmanuelMess requested changes
Please create a global constant somewhere that makes sense.

2021-09-20 19:05 UTC, VishalNehra approved these changes

2021-09-25 12:11 UTC, VishalNehra requested changes
Doesn't hide the file

2021-09-27 08:58 UTC, merged