Fix rootUri NPEs
TeamAmaze/AmazeFileManager pull request #2962
Opened 2021-10-28 23:20 UTC by EmmanuelMess

## Description

#### Issue tracker   

Fixes #2876
Fixes #2960
Fixes #2213
Fixes #2867

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2021-10-30 12:33 UTC, EmmanuelMess commented
Build test apk

2021-10-30 15:12 UTC, TranceLove approved these changes
lgtm

2021-11-04 13:19 UTC, VishalNehra commented
please rebase here

2021-11-04 19:35 UTC, EmmanuelMess commented
> please rebase here

Done

2021-11-04 23:19 UTC, VishalNehra requested changes

2021-11-04 23:19 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/filesystem/files/GenericCopyUtil.java
> +        final Uri safRoot = SafRootHolder.getUriRoot();
Need to check otg root here as well. This will not allow to copy files in otg.

2021-11-04 23:19 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/filesystem/files/GenericCopyUtil.java
> +        final Uri safRoot = SafRootHolder.getUriRoot();
Need to check otg root here as well. This will not allow to copy files in otg.

2021-11-05 23:40 UTC, closed without merging