chore: update code of conduct to 2.1
TeamAmaze/AmazeFileManager pull request #3045
Opened 2021-11-28 06:00 UTC by Bambooin

## Description

chore: update code of conduct to 2.1 

#### Issue tracker   

#### Automatic tests

- [x] Added test cases
  
#### Manual tests
- [x] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2021-11-29 00:57 UTC, EmmanuelMess submitted a review, later dismissed

2021-12-01 06:56 UTC, VishalNehra requested changes

2021-12-01 06:56 UTC, VishalNehra commented on CODE_OF_CONDUCT.md
> +[Mozilla CoC]: https://github.com/mozilla/diversity
picked from mozilla? we should use our contact details.
teamamaze.xyz
https://t.me/AmazeFileManager
support@teamamaze.xyz

2021-12-01 09:19 UTC, Bambooin commented
No, it is picked from: https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md

Just replace contact placeholder by it's advice, and nothing else changes from original file.

`You must add a contact method to the placeholder in the document so that people know how to report violations.`

2021-12-01 09:26 UTC, merged