Add support for non-tarball compressed files
TeamAmaze/AmazeFileManager pull request #3084
Opened 2021-12-27 09:35 UTC by TranceLove

## Description
Fixes #3067.

This PR adds support for various non-tarball compressed formats, including gzip, bzip, lzma and xz.

Note that these compression format has no way to tell the original file's uncompressed size and modification time without decompressing (as we know of), hence file size will show up as zero in CompressedExplorerFragment, and decompressed file will only use original file's last modification timestamp.

#### Issue tracker   
Fixes #3067

#### Automatic tests
- [x] Added test cases
  
#### Manual tests
- [x] Done  
  
- Device: Pixel 2 emulator
- OS: Android 11

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2021-12-27 23:51 UTC, EmmanuelMess requested changes

2021-12-27 23:51 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/filesystem/compressed/CompressedHelper.java
> +      decompressor = new CommonCompressedFileDecompressor(context);
Three branches that do the same thing.

2021-12-27 23:51 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/compress/GenericCompressedFileHelperTask.kt
> +class GenericCompressedFileHelperTask(
This is not "generic" is more like an "unknowable" or "unknown" CompressedHelperTask

2021-12-27 23:51 UTC, EmmanuelMess commented
Thanks for updating the tests!

2021-12-27 23:53 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/filesystem/compressed/CompressedHelper.java
> +      decompressor = new CommonCompressedFileDecompressor(context);
If this is feasable please add a comment for why all those files use the file decompressor that provides no info about size and modification.

2021-12-28 21:42 UTC, EmmanuelMess commented
Trying to open the txt inside this compressed file is broken (compressed was recompressed as zip to allow for upload, please remove from the zip before testing):
[r.txt.zip](https://github.com/TeamAmaze/AmazeFileManager/files/7786428/r.txt.zip)

2021-12-28 21:49 UTC, EmmanuelMess commented
Gzip files have broken icon:
![image](https://user-images.githubusercontent.com/10991116/147609519-7912f9f1-3d22-44cd-a301-a9c3b098876f.png)

How come Ubuntu's compressed explorer is able to show Gzipped file's original size:
![image](https://user-images.githubusercontent.com/10991116/147609545-dafa954a-5a4f-404f-bfc5-14f9d7f67c01.png)

2021-12-29 14:52 UTC, TranceLove commented
> How come Ubuntu's compressed explorer is able to show Gzipped file's original size

According to the spec, gzip does stores the file's original size at the [last 4 bytes of the whole stream](https://en.wikipedia.org/wiki/Gzip#cite_ref-4)... unless there is a strong reason to do so, I'd prefer not to walk the whole input stream for the last 4 byte footer. And also, there had been some says about the inaccuracy of this field for gzips > 4GB.

2021-12-29 16:31 UTC, EmmanuelMess commented
Very well, if you add that to a comment then it'll be ok to not have the size, etc

2021-12-30 07:18 UTC, EmmanuelMess approved these changes
Works! Tested on emulator running API 29.

2021-12-31 05:48 UTC, VishalNehra approved these changes

2021-12-31 05:48 UTC, merged