Modify String and default value on App Manager issue fix
TeamAmaze/AmazeFileManager pull request #3116
Opened 2022-01-11 08:28 UTC by pree-T

Renamed "Last Modified" to "Last Updated". Renamed "Third Party Apps" to "User Apps". Show System Apps unchecked by default. A possible fix for the issue #3026 .Kindly review.

2022-01-11 08:50 UTC, VishalNehra requested changes

2022-01-11 08:50 UTC, VishalNehra commented on app/src/main/res/values-ar/strings.xml
> +    <string name="third_party_apps">User apps</string>
Any string changes other than from values/strings.xml will be overwritten by the transifex pipeline. You should remove these changes.

2022-01-11 08:54 UTC, VishalNehra commented
spotless check fail, run `./gradlew spotlessapply` in your local.

2022-01-12 00:51 UTC, EmmanuelMess commented
Please change the string name (and delete all the old references) when changing the string in the original language, so that translations are correctly updated.

2022-01-12 00:51 UTC, EmmanuelMess requested changes
Please change the string name (and delete all the old references) when changing the string in the original language, so that translations are correctly updated.

2022-01-12 10:08 UTC, pree-T commented
I have made the suggested changes .Kindly review @EmmanuelMess @VishalNehra

2022-01-12 10:18 UTC, VishalNehra commented
Will do, meanwhile if you're interested we can assign you some important issues.

2022-01-12 19:10 UTC, EmmanuelMess submitted a review, later dismissed

2022-01-12 19:15 UTC, pree-T commented
> Will do, meanwhile if you're interested we can assign you some important issues.

Sure!

2022-01-12 19:22 UTC, VishalNehra commented
Join our telegram channel https://t.me/AmazeFileManager

2022-01-12 20:03 UTC, VishnuSanal requested changes
Thanks for the PR! Please see the comments

2022-01-12 20:03 UTC, VishnuSanal commented on app/src/main/java/com/amaze/filemanager/adapters/holders/SpecialViewHolder.kt
> +            }
Why?!

2022-01-12 20:03 UTC, VishnuSanal commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:7.0.4'
Can you revert this? We should track changes in individual PRs/commits in case something breaks due to this.  (throwback to #2833)

2022-01-13 04:19 UTC, pree-T commented
I have reverted those changes. Kindly review

2022-01-13 04:39 UTC, VishalNehra approved these changes

2022-01-13 04:41 UTC, merged

2022-01-13 05:05 UTC, VishnuSanal approved these changes

2022-01-16 17:06 UTC, VishnuSanal commented
> > Will do, meanwhile if you're interested we can assign you some important issues.
> 
> Sure!

How about #3040 @pree-T

2022-01-16 20:43 UTC, EmmanuelMess commented
@VishalNehra you reverted some of these changes?