Trap exceptions thrown when processing corrupt archives
TeamAmaze/AmazeFileManager pull request #3166
Opened 2022-02-13 03:47 UTC by TranceLove

## Description
Trap `IOException`s thrown gracefully when attempt to extract archives to a Toast.

#### Issue tracker
Addresses #3841

#### Automatic tests

- [x] Added test cases
  
#### Manual tests
- [x] Done  
  
- Device: Pixel 2 emulator
- OS: Android 11

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2022-02-13 13:34 UTC, EmmanuelMess commented
Please rebase.

2022-02-13 15:00 UTC, EmmanuelMess requested changes

2022-02-13 15:00 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/asynchronous/services/ExtractService.java
> +          xx.printStackTrace();
No printStackTrace, only `Log.e(TAG, message, throwable)`

2022-02-13 15:00 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/Extractor.java
> +    public BadArchiveNotice(@Nullable String message) {
Instead of a string can't we have the original `Exception` saved in the `BadArchiveNotice`?

2022-02-13 15:00 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/asynchronous/services/ExtractService.java
> +              TextUtils.isEmpty(e.getMessage()) ? getString(R.string.error_bad_archive_without_info, compressedPath) : getString(R.string.error_bad_archive_with_info, compressedPath, e.getMessage()))
Please also log the actual original exception.

2022-02-13 15:00 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/helpers/SevenZipExtractor.kt
> +            if (it is PasswordRequiredException || it is CorruptedInputException)
Please use {} in ifs always

2022-02-13 15:00 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/helpers/ZipExtractor.kt
> +                // Hack.
Please add a bit more explanation to this comment

2022-02-13 15:00 UTC, EmmanuelMess commented on app/src/test/java/com/amaze/filemanager/asynchronous/asynctasks/compress/AbstractCompressedHelperTaskTest.kt
> +        val emptyCallback = object :
This should be `@JvmStatic` maybe? So that it doesn't create an extra object in runtime.

2022-02-16 00:40 UTC, EmmanuelMess approved these changes
Looks good!

2022-02-24 21:25 UTC, VishalNehra approved these changes

2022-02-24 21:26 UTC, merged