Root based filesystem support for FTP server
TeamAmaze/AmazeFileManager pull request #3188
Opened 2022-02-27 15:46 UTC by TranceLove

## Description
- Root-based file system backend for Apache ftpserver backed by libsu's SuFile
- Logic to switch to root based filesystem if user selects the sharing folder is outside storage dirs which doesn't require root
- Warns user of using this root based filesystem implementation

There is one known issue though: when choosing the sharing folder, browsing above storage level directories may not work since they require root access. When using on Oneplus 2 with LineageOS 18, no directories can be seen above storage level.
(May be solved along with #3061?)

#### Issue tracker   
Fixes #1409

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  
Devices:
- GPD XD running LegacyROM (4.4.4)
- Oneplus 2 running LineageOS 18 (11)

Browsing `/data/data` or protected directories like `Android/data` shall function normally.

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2022-02-27 15:57 UTC, EmmanuelMess commented on app/src/main/res/values/strings.xml
> +    <string name="ftp_server_fallback_path_reset_prompt">FTP server shared path had been reset to internal storage as you are switching back to legacy filesystem implementation. Please select a new p
What's up with the slash at the end?

2022-03-07 01:44 UTC, EmmanuelMess requested changes
How do I test this? Is it possible to create tests for this?

2022-03-07 01:44 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/crashreport/ErrorActivity.java
> +        System.out.println(line);
`System.out.print` should not be used in Android. Please use standard log, or add the info directly into the acra report.

2022-03-07 01:44 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/filesystem/ftpserver/RootFileSystemView.kt
> +        private val logger: Logger = LoggerFactory.getLogger(RootFileSystemView::class.java)
Why are we using these loggers? Aren't android's good?

2022-03-07 01:44 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/ui/dialogs/GeneralDialogCreation.java
> +  public static MaterialDialog createAlertDialog(
Please move this to a kt object in dialogs package, annotated with `@JvmStatic`. Like dialogs in  #3205.

2022-03-07 16:23 UTC, EmmanuelMess commented
How do I test if the PR works?

2022-03-08 09:01 UTC, EmmanuelMess commented
I am having this error with any folder I set, so I cant test :sweat_smile: 

```
2022-03-08 05:59:24.039 2752-2885/? W/System.err: [NioProcessor-1] WARN org.apache.mina.util.DefaultExceptionMonitor - Unexpected exception.
2022-03-08 05:59:24.039 2752-2885/? W/System.err: org.apache.mina.core.filterchain.IoFilterLifeCycleException: onPreAdd(): sslFilter:SslFilter in (0x00000004: nio socket, server, /192.168.0.85:45176 => /192.168.0.169:2211)
2022-03-08 05:59:24.040 2752-2885/? W/System.err:     at org.apache.mina.core.filterchain.DefaultIoFilterChain.register(DefaultIoFilterChain.java:383)
2022-03-08 05:59:24.041 2752-2885/? W/System.err:     at org.apache.mina.core.filterchain.DefaultIoFilterChain.addLast(DefaultIoFilterChain.java:189)
2022-03-08 05:59:24.043 2752-2885/? W/System.err:     at org.apache.mina.core.filterchain.DefaultIoFilterChainBuilder.buildFilterChain(DefaultIoFilterChainBuilder.java:496)
2022-03-08 05:59:24.043 2752-2885/? W/System.err:     at org.apache.mina.core.polling.AbstractPollingIoProcessor.addNow(AbstractPollingIoProcessor.java:512)
2022-03-08 05:59:24.044 2752-2885/? W/System.err:     at org.apache.mina.core.polling.AbstractPollingIoProcessor.handleNewSessions(AbstractPollingIoProcessor.java:487)
2022-03-08 05:59:24.045 2752-2885/? W/System.err:     at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$400(AbstractPollingIoProcessor.java:68)
2022-03-08 05:59:24.045 2752-2885/? W/System.err:     at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1111)
2022-03-08 05:59:24.046 2752-2885/? W/System.err:     at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
2022-03-08 05:59:24.046 2752-2885/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
2022-03-08 05:59:24.046 2752-2885/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
2022-03-08 05:59:24.047 2752-2885/? W/System.err:     at java.lang.Thread.run(Thread.java:856)
2022-03-08 05:59:24.048 2752-2885/? W/System.err: Caused by: java.lang.IllegalArgumentException: TLS_ECDH_ECDSA_WITH_RC4_128_SHA is not supported.
2022-03-08 05:59:24.049 2752-2885/? W/System.err:     at org.apache.harmony.xnet.provider.jsse.SSLParametersImpl.setEnabledCipherSuites(SSLParametersImpl.java:238)
2022-03-08 05:59:24.049 2752-2885/? W/System.err:     at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.setEnabledCipherSuites(SSLEngineImpl.java:221)
2022-03-08 05:59:24.050 2752-2885/? W/System.err:     at org.apache.mina.filter.ssl.SslHandler.init(SslHandler.java:175)
2022-03-08 05:59:24.050 2752-2885/? W/System.err:     at org.apache.mina.filter.ssl.SslFilter.onPreAdd(SslFilter.java:445)
2022-03-08 05:59:24.052 2752-2885/? W/System.err:     at org.apache.mina.core.filterchain.DefaultIoFilterChain.register(DefaultIoFilterChain.java:381)
2022-03-08 05:59:24.053 2752-2885/? W/System.err: 	... 10 more
2022-03-08 05:59:29.245 2752-2885/? W/System.err: [NioProcessor-1] WARN org.apache.mina.util.DefaultExceptionMonitor - Unexpected exception.
2022-03-08 05:59:29.245 2752-2885/? W/System.err: org.apache.mina.core.filterchain.IoFilterLifeCycleException: onPreAdd(): sslFilter:SslFilter in (0x00000005: nio socket, server, /192.168.0.85:45180 => /192.168.0.169:2211)
2022-03-08 05:59:29.247 2752-2885/? W/System.err:     at org.apache.mina.core.filterchain.DefaultIoFilterChain.register(DefaultIoFilterChain.java:383)
2022-03-08 05:59:29.248 2752-2885/? W/System.err:     at org.apache.mina.core.filterchain.DefaultIoFilterChain.addLast(DefaultIoFilterChain.java:189)
2022-03-08 05:59:29.248 2752-2885/? W/System.err:     at org.apache.mina.core.filterchain.DefaultIoFilterChainBuilder.buildFilterChain(DefaultIoFilterChainBuilder.java:496)
2022-03-08 05:59:29.248 2752-2885/? W/System.err:     at org.apache.mina.core.polling.AbstractPollingIoProcessor.addNow(AbstractPollingIoProcessor.java:512)
2022-03-08 05:59:29.248 2752-2885/? W/System.err:     at org.apache.mina.core.polling.AbstractPollingIoProcessor.handleNewSessions(AbstractPollingIoProcessor.java:487)
2022-03-08 05:59:29.248 2752-2885/? W/System.err:     at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$400(AbstractPollingIoProcessor.java:68)
2022-03-08 05:59:29.249 2752-2885/? W/System.err:     at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1111)
2022-03-08 05:59:29.249 2752-2885/? W/System.err:     at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
2022-03-08 05:59:29.250 2752-2885/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
2022-03-08 05:59:29.250 2752-2885/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
2022-03-08 05:59:29.250 2752-2885/? W/System.err:     at java.lang.Thread.run(Thread.java:856)
2022-03-08 05:59:29.250 2752-2885/? W/System.err: Caused by: java.lang.IllegalArgumentException: TLS_ECDH_ECDSA_WITH_RC4_128_SHA is not supported.
2022-03-08 05:59:29.252 2752-2885/? W/System.err:     at org.apache.harmony.xnet.provider.jsse.SSLParametersImpl.setEnabledCipherSuites(SSLParametersImpl.java:238)
2022-03-08 05:59:29.252 2752-2885/? W/System.err:     at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.setEnabledCipherSuites(SSLEngineImpl.java:221)
2022-03-08 05:59:29.253 2752-2885/? W/System.err:     at org.apache.mina.filter.ssl.SslHandler.init(SslHandler.java:175)
2022-03-08 05:59:29.254 2752-2885/? W/System.err:     at org.apache.mina.filter.ssl.SslFilter.onPreAdd(SslFilter.java:445)
2022-03-08 05:59:29.254 2752-2885/? W/System.err:     at org.apache.mina.core.filterchain.DefaultIoFilterChain.register(DefaultIoFilterChain.java:381)
2022-03-08 05:59:29.255 2752-2885/? W/System.err: 	... 10 more
```

2022-03-08 11:22 UTC, TranceLove commented
Seems to me you are using [a lower API device](https://developer.android.com/reference/javax/net/ssl/SSLEngine#default-configuration-for-different-android-versions). Never mind, will prepare tests for that.

2022-03-08 11:23 UTC, EmmanuelMess commented
Yes

2022-03-16 09:07 UTC, VishalNehra approved these changes

2022-03-16 09:08 UTC, merged