Rephrased the string to shorten its length in strings.xml
TeamAmaze/AmazeFileManager pull request #3220
Opened 2022-03-14 01:47 UTC by ashway171

#### Description
Rephrased the line "Show the data and time when the file was modified last time " in strings.xml to "Show the data and time of last modification" thus reducing words.

#### Issue tracker   

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

2022-03-14 02:09 UTC, VishnuSanal requested changes
Please delete the old `String` & create a new `String` so that `Transifex` can pick that up.

2022-03-14 19:04 UTC, EmmanuelMess approved these changes

2022-03-14 19:05 UTC, EmmanuelMess commented
> Please delete the old `String` & create a new `String` so that `Transifex` can pick that up.

Meaning was not changed, translations should be mostly the same AFAIK.

2022-03-15 01:51 UTC, ashway171 commented
So, should I go for the changes?

2022-03-15 06:04 UTC, VishnuSanal requested changes

2022-03-15 06:04 UTC, VishnuSanal commented on app/src/main/res/values/strings.xml
> +    <string name="lastModifiedSummary">Show the data and time of last modification</string>
This is `date` itself!

2022-03-15 06:05 UTC, VishnuSanal commented
> So, should I go for the changes?

Nope

2022-03-15 10:59 UTC, ashway171 commented on app/src/main/res/values/strings.xml
> +    <string name="lastModifiedSummary">Show the data and time of last modification</string>
So sorry, fixing it right away

2022-03-15 13:28 UTC, VishnuSanal approved these changes

2022-03-15 15:18 UTC, merged