Fix at encrypt save as dialog, tapping the info button have no response
TeamAmaze/AmazeFileManager pull request #3235
Opened 2022-03-24 16:39 UTC by TranceLove

Fix problem at #3182: https://github.com/TeamAmaze/AmazeFileManager/pull/3182#issuecomment-1077663402

Additionally, added a contentIsHtml flag at AlertDialog.show() as the aze encryption format description is composed of HTML.

## Description

#### Issue tracker   
Addresses problem at #3182

#### Automatic tests
- [x] Added test cases
  
#### Manual tests
- [x] Done  
  
- Device: Pixel 2 emulator
- OS: Android 11

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #3182

2022-03-25 12:05 UTC, VishnuSanal approved these changes

2022-03-25 12:37 UTC, VishnuSanal requested changes
Awesome work! Please consider these too.

1. Can we convert the info button on encrypt dialog to a TextView below the checkbox? As of now, it has a greater chance of getting ignored. As suggested on #3156 Or as Vishal suggested, the dialog appears just when the checkbox is checked.

2. The text fields can be empty and the OK button can be clicked! (some ways to do this would be to check the checkbox, uncheck the checkbox & focus on a text field etc) Can we have checks for this? It's okay if these are checked even after O.K button is clicked, we can set error to the TextInputLayout then too.

2022-03-26 21:22 UTC, VishalNehra commented
@TranceLove can you convert this pr to draft please if it's in wip

2022-03-30 16:24 UTC, TranceLove commented
Let's see if this is what you're looking for.

![Screenshot_20220331_001928](https://user-images.githubusercontent.com/251819/160883586-8b1de6d9-7402-41e2-ad30-f4cc70cdce29.png)

![Screenshot_20220331_001942](https://user-images.githubusercontent.com/251819/160883595-84cfa240-6887-4b4a-8496-e3fd7fbec533.png)

Meanwhile, because of the way we do field validations, this is probably the best we may have for the form. But please feel free to comment on a better way to do form validation on situations like this - I too think the error messages pop up at the wrong time.

2022-03-30 18:18 UTC, VishalNehra commented
> Let's see if this is what you're looking for.
> 
> Meanwhile, because of the way we do field validations, this is probably the best we may have for the form. But please feel free to comment on a better way to do form validation on situations like this - I too think the error messages pop up at the wrong time.

This looks good to me. Please also mention that amaze encryption is based on aes as well.

2022-04-01 18:22 UTC, VishnuSanal approved these changes

2022-04-01 18:22 UTC, VishnuSanal commented on app/src/main/res/values/strings.xml
> +        <p>Amaze\'s Encryption Format is also based on AES encryption; but different from AESCrypt format, it can only be decrypted by this device; also you must not uninstall Amaze File Manager from
Should we add that they shouldn't change the screen lock too?

2022-04-04 06:59 UTC, VishnuSanal approved these changes
🚀

2022-04-16 06:05 UTC, VishalNehra approved these changes

2022-04-16 06:05 UTC, merged