Exception handling for 7z entries without timestamps
TeamAmaze/AmazeFileManager pull request #3254
Opened 2022-04-14 16:53 UTC by TranceLove

It seems [such archives can be created intentionally](https://sourceforge.net/p/sevenzip/discussion/45797/thread/61905a4c/).

For 7z archives having entries with no timestamp,
- they will show as 00:00:00 1970-01-01 when in file manager view
- they will have last modified date = current timestamp on extracting

## Description

#### Issue tracker   
Fixes #3035

#### Automatic tests
- [x] Added test cases
  
#### Manual tests
- [x] Done  
  
- Device: Pixel 2 emulator
- OS: Android 11

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2022-04-16 06:03 UTC, VishalNehra approved these changes

2022-04-22 21:42 UTC, EmmanuelMess requested changes

2022-04-22 21:42 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/compress/SevenZipHelperCallable.kt
> +                            runCatching { entry.lastModifiedDate.time }.getOrElse { 0L },
What does this catch? This should be more explicit of what it does.

2022-04-22 21:42 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/helpers/SevenZipExtractor.kt
> +                }.getOrElse { System.currentTimeMillis() }
Can't we have an "unknown" state?

2022-04-23 21:47 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/helpers/SevenZipExtractor.kt
> +                }.getOrElse { System.currentTimeMillis() }
can't seem like we can have

2022-04-23 21:47 UTC, VishalNehra approved these changes

2022-04-23 21:47 UTC, merged

2022-04-23 21:56 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/helpers/SevenZipExtractor.kt
> +                    Log.w(javaClass.simpleName, "Unable to get modified date for 7zip file")
These should use `TAG` why was this fixed like this?