Handle external intents to open folder locations
TeamAmaze/AmazeFileManager pull request #3305
Opened 2022-05-08 17:16 UTC by VishnuSanal

## Description

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  
- Device: Pixel XL API 31 Emulator
  - OS: Android 12
  - Tested by locating a file from AFU both from internal storage & SD card
- Device: Realme Narzo 20A
  - OS: Android 11
  - Tested by locating a file from AFU from internal storage

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2022-05-08 17:20 UTC, VishnuSanal commented
Build test APK

2022-05-08 17:23 UTC, VishalNehra commented
That's it?

2022-05-08 17:26 UTC, VishnuSanal commented
@VishalNehra Um, yes... The main problem was a trailing /storage_root to the path. I used FileUtils#fromContentUri to get rid of that - seems like that works during initial testing. Need more testing though, from different file locations.

2022-05-10 11:30 UTC, VishalNehra commented
Working great! Nice work! However, as asked originally, it's better if we can also scroll to the item and highlight it. It's super useful specially for places with large directory items.

2022-05-10 11:31 UTC, VishnuSanal commented
@VishalNehra Oops! I forgot about that altogether 🙈 Will look into it, ASAP

2022-05-10 15:33 UTC, VishnuSanal commented
> Working great! Nice work! However, as asked originally, it's better if we can also scroll to the item and highlight it. It's super useful specially for places with large directory items.

@VishalNehra AFU only gives the path to the containing folder! How to scroll to the selected file with this path?

2022-05-10 17:33 UTC, VishnuSanal commented
@VishalNehra Nope.

2022-05-10 17:54 UTC, VishnuSanal commented
@VishalNehra Maybe, we can do something for AFU only, and ship it as is for intents from other apps.

Add the file name or path to the bundle from AFU, with key starting with our package name. Then, we can check for it & handle that case.

What say?

2022-05-10 20:05 UTC, VishalNehra requested changes

2022-05-10 20:05 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt
> +    fun getScrollPosition(title: String): Int {
Can you use mutable livedata to process this index background and publish?

2022-05-15 09:34 UTC, VishalNehra requested changes

2022-05-15 09:34 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt
> +                    mutableLiveData.value = index
use `postValue` instead of `setValue`

2022-05-15 09:34 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt
> +        GlobalScope.launch(Dispatchers.IO) {
Use `viewModelScope.launch(Dispatchers.IO)` instead of GlobalScope

2022-05-16 11:39 UTC, VishalNehra commented
Why is the build failing?

2022-05-16 13:57 UTC, VishalNehra commented
Try running cleaning project and rebuilding.

2022-05-17 21:09 UTC, VishalNehra approved these changes

2022-05-17 21:10 UTC, merged