Add a splash screen when Amaze loads
TeamAmaze/AmazeFileManager pull request #3442
Opened 2022-08-20 14:53 UTC by dhruvpatidar359

Signed-off-by: dhruv [dhruvpatidar35@gmail.com](mailto:dhruvpatidar35@gmail.com)
closes https://github.com/TeamAmaze/AmazeFileManager/issues/3139

 Description

Issue tracker   
Fixes https://github.com/TeamAmaze/AmazeFileManager/issues/3139

Automatic tests

- [ ] Added test cases
  
 Manual tests
- [ ] Done  
  

 Build tasks success  

Successfully running following tasks on local:
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

2022-08-21 03:53 UTC, dhruvpatidar359 commented
hello @EmmanuelMess   can you please review this PR .

2022-08-21 05:51 UTC, dhruvpatidar359 commented
@EmmanuelMess  may you please help me how i can i resolve these checks , as am not getting a proper solution for it .

2022-08-21 22:38 UTC, EmmanuelMess requested changes
The image used should not be a png, it should be an svg.

2022-08-21 22:38 UTC, EmmanuelMess commented on app/build.gradle
> +    implementation 'androidx.core:core-splashscreen:1.0.0-beta01'
You might not want to use the splash screen library if it has API level issues.

2022-08-21 22:38 UTC, EmmanuelMess commented
You should run spotlessApply to fix check spotless.

2022-08-21 22:40 UTC, EmmanuelMess commented
```

com.amaze.filemanager.asynchronous.asynctasks.SshDeleteTaskTest > testDeleteSshFileAccessDenied[16] FAILED
    java.lang.NoSuchMethodError: 'android.graphics.drawable.Drawable android.content.res.Resources$Theme.getDrawable(int)'
        at androidx.core.splashscreen.SplashScreen$Impl.install(SplashScreen.kt:264)
        at androidx.core.splashscreen.SplashScreen.install(SplashScreen.kt:189)
        at androidx.core.splashscreen.SplashScreen.access$install(SplashScreen.kt:121)
        at androidx.core.splashscreen.SplashScreen$Companion.installSplashScreen(SplashScreen.kt:146)
        at androidx.core.splashscreen.SplashScreen.installSplashScreen(SplashScreen.kt)
        at com.amaze.filemanager.ui.activities.MainActivity.onCreate(MainActivity.java:331)
        at android.app.Activity.performCreate(Activity.java:5008)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:284)
        at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:113)
        at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:203)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:113)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:118)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:103)
        at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:33)
        at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:38)
        at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:265)
        at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:195)
        at com.amaze.filemanager.asynchronous.asynctasks.AbstractDeleteTaskTestBase.doTestDeleteFileAccessDenied(AbstractDeleteTaskTestBase.kt:107)
        at com.amaze.filemanager.asynchronous.asynctasks.SshDeleteTaskTest.testDeleteSshFileAccessDenied(SshDeleteTaskTest.kt:53)

```

Are you using getDrawable on the wrong API level?

2022-08-22 09:49 UTC, dhruvpatidar359 commented
@EmmanuelMess  ok I will remove the library.
May you please explain the meaning of making the splash screen by hand as you said earlier

2022-08-23 01:02 UTC, EmmanuelMess commented
> May you please explain the meaning of making the splash screen by hand as you said earlier

I think you can use an activity to show an image, and start the main activity from there, so that the main activity loads with the initial image as background.

2022-08-23 03:01 UTC, dhruvpatidar359 commented
@EmmanuelMess  , i am not able to create a new activity as the minsdk is 14 but requires 16(minimum) for that i have to chaange the minsdk 14 to 16
![image](https://user-images.githubusercontent.com/103873587/186059840-19fa35d5-2465-4d7e-b354-5d073878a3d1.png)

2022-08-24 21:03 UTC, EmmanuelMess commented
> @EmmanuelMess , i am not able to create a new activity as the minsdk is 14 but requires 16(minimum) for that i have to change the minsdk 14 to 16 ![image](https://user-images.githubusercontent.com/103873587/186059840-19fa35d5-2465-4d7e-b354-5d073878a3d1.png)

That's with the dialog, you should create it by hand, or convert what the dialog creates to an API 14 compatible version.

2022-08-26 11:44 UTC, closed without merging

2022-08-26 14:35 UTC, dhruvpatidar359 commented
@EmmanuelMess  is there any svg available for the icon in the project as i am not able to find it ?