Settings export/import
TeamAmaze/AmazeFileManager pull request #3552
Opened 2022-10-08 16:34 UTC by VishnuSanal

## Description

#### Issue tracker   
Fixes #3176

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  

- Device: Pixel 3A Emulator
- OS: Android Tiramisu x86_64

#### Build tasks success
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2022-10-15 13:58 UTC, EmmanuelMess requested changes

2022-10-15 13:58 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/ui/fragments/preferencefragments/BackupPrefsFragment.kt
> +                for ((key, value) in map) try {
Use when syntax

2022-10-15 13:58 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/ui/fragments/preferencefragments/BackupPrefsFragment.kt
> +            try {
This has a few try catch nested, you should collect all errors and provide the user with error based feedback. Maybe print the exception message to a toast?

2022-10-15 13:58 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/ui/fragments/preferencefragments/BackupPrefsFragment.kt
> +            Log.e(TAG, "read import file: $uri")
Why the log? why is this an error log?

2022-10-15 13:58 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/ui/fragments/preferencefragments/BackupPrefsFragment.kt
> +            Log.e(TAG, "wrote export to: ${file.absolutePath}")
Logs error.

2022-10-15 13:59 UTC, EmmanuelMess commented
Please add a test that exports from one version and imports to another. How does this manage adding settings?

2022-10-15 14:47 UTC, VishnuSanal commented on app/src/main/java/com/amaze/filemanager/ui/fragments/preferencefragments/BackupPrefsFragment.kt
> +            Log.e(TAG, "read import file: $uri")
whoops, my bad, it should be a `Log#i`

2022-10-16 07:03 UTC, VishnuSanal commented
> Please add a test that exports from one version and imports to another.

sure.

> How does this manage adding settings?

settings would be imported only if it is present in the backup file, else it is left to the user to set it manually.

2022-12-25 08:43 UTC, VishalNehra commented
@VishnuSanal  can you fix the codacy failures here please?

2022-12-26 12:42 UTC, VishnuSanal commented
> @VishnuSanal can you fix the codacy failures here please?

sure, but can we ignore the missing documentation warnings?

2022-12-26 14:14 UTC, VishnuSanal commented
> > @VishnuSanal can you fix the codacy failures here please?
> 
> sure, but can we ignore the missing documentation warnings?

NVM, fixed them.

2022-12-31 13:58 UTC, VishalNehra approved these changes

2022-12-31 13:58 UTC, merged

2023-01-02 03:24 UTC, bananaking24 commented
how do i use it im trying to install amaze but idk howwww