Fixes #2417
TeamAmaze/AmazeFileManager pull request #3571
Opened 2022-10-13 17:52 UTC by VishnuSanal

## Description

#### Issue tracker   
Fixes #2417

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  

- Device: Pixel 3A
- OS: Android Tiramisu x86_64
- Device: Realme Narzo 20A
- OS: Android 11

#### Build tasks success
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2022-10-15 13:51 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/ui/views/drawer/Drawer.java
> +                    if (safIntent.resolveActivity(mainActivity.getPackageManager()) != null)
Remember to add the curly brackets on ifs as per the guidelines

2022-10-15 13:52 UTC, EmmanuelMess requested changes
You should use a Snackbar if a view is available.

2022-10-25 21:57 UTC, VishalNehra requested changes

2022-10-25 21:57 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.kt
> +                                if (intent.resolveActivity(mainActivity.packageManager) != null) {
Can you create a kotlin extension function on `Intent` instead of writing if else conditions everywhere please? Take callbacks as args.

2022-11-18 12:33 UTC, VishalNehra approved these changes

2022-11-18 12:33 UTC, merged

2022-11-18 14:56 UTC, VishnuSanal commented on app/src/main/java/com/amaze/filemanager/ui/Extensions.kt
> +fun Intent.runIfDocumentsUIExists(mainActivity: MainActivity, callback: Runnable) {
> Avoid passing mainActivity instance too much

Okay, I did it here cuz I didn't find any other way to get a `View` to show a `SnackBar`