Drive size info in navigation drawer
TeamAmaze/AmazeFileManager pull request #3591
Opened 2022-10-24 19:46 UTC by VishnuSanal

## Description

#### Issue tracker   
Fixes #3383

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  

- Device: Pixel 3A
- OS: Android Tiramisu x86_64
- Device: Realme Narzo 20A
- OS: Android 11
- Device: Pixel 2
- OS: Android API 16

#### Build tasks success
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2022-10-26 15:23 UTC, VishnuSanal commented
<img src="https://user-images.githubusercontent.com/50027064/198067372-dc58fce8-c1c3-40a7-bc80-45e73b530242.png" height=800 />

2022-11-04 01:24 UTC, EmmanuelMess requested changes

2022-11-04 01:24 UTC, EmmanuelMess commented on app/src/main/res/values/strings.xml
> +    <string name="free_of">"free of</string>
Use a string with placeholders.

2022-11-04 01:24 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/ui/views/drawer/Drawer.java
> +        String.format(
No, use the format provided by getString

2022-11-04 01:24 UTC, EmmanuelMess commented on app/src/main/java/com/amaze/filemanager/ui/views/drawer/Drawer.java
> +  private void addNewItem(
Add NonNull for menu and metadata

2022-11-16 22:36 UTC, VishalNehra approved these changes

2022-11-16 22:36 UTC, merged