Fix NetworkOnMainThreadException on HybridFile.getUsableSpace() and HybridFileParcelable.isDirectory()
TeamAmaze/AmazeFileManager pull request #3999
Opened 2023-11-28 15:44 UTC by TranceLove

## Description

- Fix `SmbFile.getDiskSpace()` was not wrapped with RxJava in `HybridFile.getUsableSpace()` for network calls
- Added `HybridFileParcelable.isDirectory(Context)` that made copy and paste remote folders unnecessary long, especially when remote is SSH server

#### Issue tracker   
Fixes #3982

#### Manual tests
- [x] Done  
  
Device:
- Pixel 5 emulator running Android 11
- Fairphone 3 running LineageOS 20 (13)

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

2023-11-30 07:41 UTC, VishalNehra requested changes

2023-11-30 07:41 UTC, VishalNehra commented on app/src/main/java/com/amaze/filemanager/filesystem/HybridFileParcelable.java
> +    return isDirectory;
this may lead to issues, can you just return isDirectory only in case of SMB if you've tested it properly.

2023-12-02 06:52 UTC, TranceLove commented
Added an alert dialog which will pop up when attempt to load SMB server root without credentials failed.

Per Samba docs it indicates it's a good practice to restrict unauthenticated access to SMB server root, or in other words, the `IPC$` share. But it's decent that some feedback to user is necessary.

<img src="https://github.com/TeamAmaze/AmazeFileManager/assets/251819/0f5ad317-a4e5-4493-88d3-955db73ef155" width="270" height="480">

2023-12-06 20:21 UTC, VishalNehra approved these changes

2023-12-06 20:22 UTC, merged