Fix navigation buttons barely visible on dark and light mode
TeamAmaze/AmazeFileManager pull request #4211
Opened 2024-07-04 22:20 UTC by Thejas775

## Description

This PR addresses the issue where navigation buttons are barely visible on Motorola devices when using the White/Day theme. The visibility issue is caused by the navigation bar color blending with the background, making the buttons hard to see.

#### Issue tracker   
Fixes #3535 

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [ ] Done

2024-07-05 07:21 UTC, VishnuSanal requested changes
hi @Thejas775, happy to see your interest in contributing to amaze!
but, the approach you used was not the expected solution. currently, you are changig the BG color of nav bar. the issue is to change the colors of nav icons. can you try whether something like [this](https://stackoverflow.com/a/77240345/9652621) this works?

2024-07-05 09:45 UTC, Thejas775 commented
> hi @Thejas775, happy to see your interest in contributing to amaze! but, the approach you used was not the expected solution. currently, you are changig the BG color of nav bar. the issue is to change the colors of nav icons. can you try whether something like [this](https://stackoverflow.com/a/77240345/9652621) this works?

Okay sure.

2024-07-20 15:14 UTC, VishnuSanal commented
@Thejas775 any updates here?

2024-07-20 15:20 UTC, Thejas775 commented
> @Thejas775 any updates here?

Hey, sorry I was busy with something. I tried the way described in the stackoverflow but it didn't work

2024-07-20 17:16 UTC, VishnuSanal commented
> I tried the way described in the stackoverflow but it didn't work

oh, I have tried those when I was reviewing your PR & they worked, IIRC. you can push your changes -- I will take a look.

2024-07-20 19:56 UTC, Thejas775 commented
> > I tried the way described in the stackoverflow but it didn't work
> 
> oh, I have tried those when I was reviewing your PR & they worked, IIRC. you can push your changes -- I will take a look.

Which one to push the new one from stack overflow?

2024-07-20 19:58 UTC, VishnuSanal commented
@Thejas775 Um... Yep, the one you were facing issues with -- the one that didn't work.

2024-10-14 17:46 UTC, VishnuSanal commented
hi Thejas, is this still being worked upon? can I take this PR over?

2024-10-14 17:50 UTC, Thejas775 commented
> hi Thejas, is this still being worked upon? can I take this PR over?

Hey sorry, I was busy with something. Please take over this PR.

2024-10-15 15:09 UTC, VishnuSanal commented
- removed code from `MainActivity` & `AboutActivity` since it was redundant. both of them inherit `ThemedActivity` & the same was done there too.

- removed setting the nav bar colors since the default android colors were better than the ones we set + they were the cause of this issue leading to usability issues too.

2026-07-15 21:35 UTC, EmmanuelMess approved these changes
Tested on Pixel 9 API 34 emulator with 3 button navigation activated.

2026-07-15 21:36 UTC, EmmanuelMess commented
@VishnuSanal this requires your review too, as you had asked for changes.

2026-07-16 04:41 UTC, VishnuSanal approved these changes

2026-07-16 04:41 UTC, merged